//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novaelectrosbit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Novaelectrosbit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам должно быть не менее 18 лет.
        /// </summary>
        public static string BirthdateToolTip {
            get {
                return ResourceManager.GetString("BirthdateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Придумайте пароль *.
        /// </summary>
        public static string ComeUpPassS {
            get {
                return ResourceManager.GetString("ComeUpPassS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зачислен.
        /// </summary>
        public static string CreditedStr {
            get {
                return ResourceManager.GetString("CreditedStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный E-mail.
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email *.
        /// </summary>
        public static string EmailS {
            get {
                return ResourceManager.GetString("EmailS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО должно начинаться с заглавной буквы и содержать не менее 2х символов.
        /// </summary>
        public static string FIOError {
            get {
                return ResourceManager.GetString("FIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать не менее 8 знаков, включая цифры, и большие, и маленькие буквы латинского алфавита.
        /// </summary>
        public static string IconInfoToolTip {
            get {
                return ResourceManager.GetString("IconInfoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам необходимо заполнить все обязательные поля.
        /// </summary>
        public static string NeedToFillRequired {
            get {
                return ResourceManager.GetString("NeedToFillRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        public static string PasswordsError {
            get {
                return ResourceManager.GetString("PasswordsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательно для заполнения.
        /// </summary>
        public static string RequiredFillIn {
            get {
                return ResourceManager.GetString("RequiredFillIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль *.
        /// </summary>
        public static string RetryPassS {
            get {
                return ResourceManager.GetString("RetryPassS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СОХРАНИТЬ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобильный телефон *.
        /// </summary>
        public static string TelephoneS {
            get {
                return ResourceManager.GetString("TelephoneS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя *.
        /// </summary>
        public static string UserFirstnameS {
            get {
                return ResourceManager.GetString("UserFirstnameS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество пользователя.
        /// </summary>
        public static string UserMiddlename {
            get {
                return ResourceManager.GetString("UserMiddlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия пользователя.
        /// </summary>
        public static string UserSurname {
            get {
                return ResourceManager.GetString("UserSurname", resourceCulture);
            }
        }
    }
}
