//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novaelectrosbit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Counter()
        {
            this.MeterReadings = new HashSet<MeterReading>();
            this.Requisites = new HashSet<Requisite>();
        }
    
        public string Number { get; set; }
        public System.DateTime InstallDate { get; set; }
        public double CounterValue { get; set; }
        public int CounterBrandID { get; set; }
        public int SettingIndications { get; set; }
        public double TransformCoefficient { get; set; }
        public System.DateTime MPIEndDate { get; set; }
        public int InstallPlaceID { get; set; }
        public int ExplResponsiblePersonID { get; set; }
        public int NetworkOrganisationID { get; set; }
        public int BuildTypeID { get; set; }
        public string ASKUESystemName { get; set; }
    
        public virtual BuildType BuildType { get; set; }
        public virtual CounterBrand CounterBrand { get; set; }
        public virtual InstallPlace InstallPlace { get; set; }
        public virtual NetworkOrganisation NetworkOrganisation { get; set; }
        public virtual ResponsiblePerson ResponsiblePerson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeterReading> MeterReadings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisite> Requisites { get; set; }
    }
}
