//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novaelectrosbit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterReading
    {
        public int ID { get; set; }
        public string CounterNumber { get; set; }
        public System.DateTime IndicationsDate { get; set; }
        public int Indications { get; set; }
    
        public virtual Counter Counter { get; set; }
    }
}
