//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novaelectrosbit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payer
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ResponsiblePersonID { get; set; }
        public string RequisitesPersonalAccount { get; set; }
    
        public virtual Requisite Requisite { get; set; }
        public virtual ResponsiblePerson ResponsiblePerson { get; set; }
        public virtual User User { get; set; }
    }
}
