//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novaelectrosbit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationAddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistrationAddress()
        {
            this.Requisites = new HashSet<Requisite>();
        }
    
        public int ID { get; set; }
        public int LocalityID { get; set; }
        public int PrefixID { get; set; }
        public string House { get; set; }
        public Nullable<int> Flat { get; set; }
    
        public virtual Locality Locality { get; set; }
        public virtual Prefix Prefix { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisite> Requisites { get; set; }
    }
}
