//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novaelectrosbit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitesPayment
    {
        public int ID { get; set; }
        public string PersonalAccount { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public System.DateTime PayDate { get; set; }
        public double PayAmount { get; set; }
        public double BalanceAfterPay { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual Requisite Requisite { get; set; }
    }
}
